In [86]:
# 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
# zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
# ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
# Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
# Полученные значения должны быть равны.
# Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
# а затем с использованием функций из библиотек numpy и pandas.
import numpy as np
import pandas as pd
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [87]:
ks = ([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

[401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [88]:
cov1 = np.mean(zp*ks) - np.mean(zp) * np.mean(ks)
cov1

9157.839999999997

In [89]:
cov2 = np.cov(zp,ks,ddof=0)
cov2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [90]:
r = cov1 / (np.std(zp) * np.std(ks))
r

0.8874900920739158

In [91]:
cor = np.corrcoef(zp,ks)
cor

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [92]:
# 2. Измерены значения IQ выборки студентов,
# обучающихся в местных технических вузах:
# 131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
# Известно, что в генеральной совокупности IQ распределен нормально.
# Найдите доверительный интервал для математического ожидания с надежностью 0.95.
from math import sqrt
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
M = iq.mean()
S = iq.std(ddof=1)
n = len(iq)
x1 = M - 2.262 * S / sqrt(n)
x2 = M + 2.262 * S / sqrt(n)
print(F'Доверительный интервал: {x1}, {x2}')

Доверительный интервал: 110.55660776308164, 125.64339223691834


In [93]:
# 3. Известно, что рост футболистов в сборной распределен нормально
# с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
# среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95
M = 174.2
S = sqrt(25)
n = 27
x1 = M - 1.96 * S / sqrt(n)
x2 = M + 1.96 * S / sqrt(n)
print(F'Доверительный интервал: {x1}, {x2}')

Доверительный интервал: 172.31398912064722, 176.08601087935276
